"""empty message

Revision ID: 0825bfe10c2e
Revises: fd29474e5d27
Create Date: 2026-03-05 10:46:16.253303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0825bfe10c2e'
down_revision = 'fd29474e5d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensayo_emu', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('param_emu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('param_emu', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('ensayo_emu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
