"""empty message

Revision ID: 186aad13aa65
Revises: 0825bfe10c2e
Create Date: 2026-03-05 10:51:34.631459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186aad13aa65'
down_revision = '0825bfe10c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensayo_emu',
    sa.Column('Lote', sa.String(length=100), nullable=False),
    sa.Column('RA', sa.Float(), nullable=False),
    sa.Column('Viscosidad', sa.Float(), nullable=False),
    sa.Column('Tamiz', sa.Float(), nullable=False),
    sa.Column('Penetracion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Lote'], ['OPEMU.Lote'], ),
    sa.PrimaryKeyConstraint('Lote')
    )
    op.create_table('param_emu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Lote', sa.String(length=100), nullable=False),
    sa.Column('RA', sa.Float(), nullable=False),
    sa.Column('Viscosidad', sa.Float(), nullable=False),
    sa.Column('Tamiz', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Lote'], ['OPEMU.Lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('param_emu')
    op.drop_table('ensayo_emu')
    # ### end Alembic commands ###
