"""empty message

Revision ID: a65faef93e60
Revises: 
Create Date: 2026-03-04 15:12:12.089599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65faef93e60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AsfaltoMP',
    sa.Column('Cod_MP', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('PEN', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Cod_MP')
    )
    op.create_table('OPEMU',
    sa.Column('Lote', sa.String(length=100), nullable=False),
    sa.Column('Cod_MP', sa.String(length=100), nullable=False),
    sa.Column('Tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['Cod_MP'], ['AsfaltoMP.Cod_MP'], ),
    sa.PrimaryKeyConstraint('Lote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OPEMU')
    op.drop_table('AsfaltoMP')
    # ### end Alembic commands ###
