"""empty message

Revision ID: b5f2153ed287
Revises: 1e61d34dd92f
Create Date: 2026-03-05 14:27:00.864191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f2153ed287'
down_revision = '1e61d34dd92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('param_emu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Lote', sa.String(length=100), nullable=False),
    sa.Column('RA', sa.Float(), nullable=False),
    sa.Column('Viscosidad', sa.Float(), nullable=False),
    sa.Column('Tamiz', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Lote'], ['OPEMU.Lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('param_emu')
    # ### end Alembic commands ###
