"""empty message

Revision ID: fd29474e5d27
Revises: a65faef93e60
Create Date: 2026-03-04 15:37:05.428168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd29474e5d27'
down_revision = 'a65faef93e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensayo_emu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Lote', sa.String(length=100), nullable=False),
    sa.Column('RA', sa.Float(), nullable=False),
    sa.Column('Viscosidad', sa.Float(), nullable=False),
    sa.Column('Tamiz', sa.Float(), nullable=False),
    sa.Column('Penetracion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Lote'], ['OPEMU.Lote'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('param_emu',
    sa.Column('Lote', sa.String(length=100), nullable=False),
    sa.Column('RA', sa.Float(), nullable=False),
    sa.Column('Viscosidad', sa.Float(), nullable=False),
    sa.Column('Tamiz', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Lote'], ['OPEMU.Lote'], ),
    sa.PrimaryKeyConstraint('Lote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('param_emu')
    op.drop_table('ensayo_emu')
    # ### end Alembic commands ###
